
const edges = [{
    source: 41,
    target: 44,
    weight: 29,
    label: 'Poaceae'
}, {
    source: 24,
    target: 43,
    weight: 61,
    label: 'Myrtaceae'
}, {
    source: 47,
    target: 2,
    weight: 42,
    label: 'Oleaceae'
}, {
    source: 38,
    target: 6,
    weight: 17,
    label: 'Asteraceae'
}, {
    source: 32,
    target: 24,
    weight: 44,
    label: 'Asteraceae'
}, {
    source: 24,
    target: 41,
    weight: 60,
    label: 'Hydrophyllaceae'
}, {
    source: 43,
    target: 42,
    weight: 75,
    label: 'Pottiaceae'
}, {
    source: 30,
    target: 27,
    weight: 97,
    label: 'Apocynaceae'
}, {
    source: 45,
    target: 8,
    weight: 58,
    label: 'Solanaceae'
}, {
    source: 34,
    target: 17,
    weight: 31,
    label: 'Dryopteridaceae'
}, {
    source: 3,
    target: 23,
    weight: 57,
    label: 'Haloragaceae'
}, {
    source: 50,
    target: 5,
    weight: 1,
    label: 'Cyperaceae'
}, {
    source: 39,
    target: 6,
    weight: 42,
    label: 'Asteraceae'
}, {
    source: 18,
    target: 33,
    weight: 20,
    label: 'Asteraceae'
}, {
    source: 34,
    target: 31,
    weight: 89,
    label: 'Amaranthaceae'
}, {
    source: 31,
    target: 19,
    weight: 11,
    label: 'Verrucariaceae'
}, {
    source: 48,
    target: 16,
    weight: 78,
    label: 'Malvaceae'
}, {
    source: 30,
    target: 41,
    weight: 12,
    label: 'Apiaceae'
}, {
    source: 32,
    target: 48,
    weight: 27,
    label: 'Scrophulariaceae'
}, {
    source: 39,
    target: 38,
    weight: 9,
    label: 'Polemoniaceae'
}, {
    source: 26,
    target: 9,
    weight: 29,
    label: 'Campanulaceae'
}, {
    source: 38,
    target: 9,
    weight: 28,
    label: 'Linaceae'
}, {
    source: 29,
    target: 28,
    weight: 73,
    label: 'Liliaceae'
}, {
    source: 35,
    target: 38,
    weight: 72,
    label: 'Caryophyllaceae'
}, {
    source: 47,
    target: 12,
    weight: 26,
    label: 'Polygonaceae'
}, {
    source: 12,
    target: 49,
    weight: 93,
    label: 'Asteraceae'
}, {
    source: 30,
    target: 2,
    weight: 96,
    label: 'Zingiberaceae'
}, {
    source: 10,
    target: 27,
    weight: 54,
    label: 'Liliaceae'
}, {
    source: 29,
    target: 18,
    weight: 49,
    label: 'Asteraceae'
}, {
    source: 44,
    target: 30,
    weight: 91,
    label: 'Asteraceae'
}];

export default edges;
